### ISSUE TITLE
Sorcerer Points macro not converting slots into points and viceversa

### ISSUE THREAD

**Issue by adamspecial** [Kekilla0/Personal-Macros#12]
I have tried this in a blank 5e world with no modules, and in a world with the various useful mods (furnace, midi, etc.) but it gives me the exact same error.

For using metamagic, it seems there is no problem. But when trying to convert spell slot into sorcery points, or viceversa, this happens. It does detect spell slots, since if the actor has full slots on a level it doesn't let you recover them, even though by the rules there is no such thing (a sorcerer _can_ go over their maximum daily slots when creating slots with sorcery points).

I don't have the slightest idea on what could be wrong though.

![screenshot 1](https://user-images.githubusercontent.com/1870427/114320934-b4d04300-9b18-11eb-9ed1-324738f9b468.png)
![screenshot 2](https://user-images.githubusercontent.com/1870427/114320940-bac62400-9b18-11eb-866d-3a27313ddb86.png)

**Comment by Kekilla0** [comment]
This is more or less discontinued.
