### ISSUE TITLE
Uncaught (in promise) Error: Maximum depth exceeded

### ISSUE THREAD

**Issue by theMagius0** [Kekilla0/Personal-Macros#15]
Good afternoon, Matthew.

I am working with your Personal-Macros/SFRPG/GM Macros/Sell.js macro inside Foundry 7.10.

For the most part, everything is working correctly.  However, on _very rare_ occasions the script throws an error as follows:

`Uncaught (in promise) Error: Maximum depth exceeded`

It's terribly difficult to reproduce but, from what I understand this is some kind of React JS error related to the render().  However, I don't have enough React JS expertise to know what the full issue is.

Any chance you may have encountered this error during your coding, as well?  And would you possibly have a fix?

Thx,

**Comment by Kekilla0** [comment]
Removed due to incompatibility with 0.8.X
